sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    bucket-name: food-serve
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: OZvQF2hdN0cIeYnxeKU7qImTVVz9YT
    access-key-id: LTAI5t9sCR7o3u2rPgwE4ERT
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: wxa0b06bd5d4acef45
    secret: 15417e01ff46523e898e8e83192edd93
