sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    bucket-name: food-serve
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: xxxxx
    access-key-id: xxxxxxx
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: xxxxxx
    secret: xxxxxxx
